# Generated by Django 5.2.14 on 2026-05-24 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icono')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Tipo de módulo',
                'verbose_name_plural': 'Tipos de módulos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'verbose_name': 'Grupo - Permiso',
                'verbose_name_plural': 'Grupos - Permisos',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='security_groups', through='security.GroupPermission', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icono')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible en menú')),
                ('is_vertical', models.BooleanField(default=False, verbose_name='Menú vertical')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('permits', models.ManyToManyField(blank=True, related_name='modules', to='auth.permission', verbose_name='Permisos asociados')),
                ('module_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='security.moduletype', verbose_name='Tipo de módulo')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['module_type__order', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='grouppermission',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.module'),
        ),
        migrations.CreateModel(
            name='GroupModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_modules', to='security.group')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_groups', to='security.module')),
            ],
            options={
                'verbose_name': 'Grupo - Módulo',
                'verbose_name_plural': 'Grupos - Módulos',
                'unique_together': {('group', 'module')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='groups', through='security.GroupModule', to='security.module'),
        ),
        migrations.AlterUniqueTogether(
            name='grouppermission',
            unique_together={('group', 'module', 'permission')},
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['url'], name='security_mo_url_c51b44_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['is_active', 'is_visible'], name='security_mo_is_acti_c99e62_idx'),
        ),
    ]
