# Generated by Django 5.2.14 on 2026-06-10 06:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Nombre")),
                (
                    "client_id",
                    models.CharField(
                        default=uuid.uuid4, max_length=100, unique=True, verbose_name="Client ID"
                    ),
                ),
                ("client_secret", models.CharField(max_length=255, verbose_name="Client Secret")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Actualizado")),
            ],
            options={
                "verbose_name": "Proveedor externo",
                "verbose_name_plural": "Proveedores externos",
                "ordering": ["name"],
            },
        ),
    ]
