# Generated by Django 5.2.14 on 2026-06-14 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_externalprovider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmodule',
            options={'verbose_name': 'Grupo - Modulo', 'verbose_name_plural': 'Grupos - Modulos'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['module_type__order', 'order', 'name'], 'verbose_name': 'Modulo', 'verbose_name_plural': 'Modulos'},
        ),
        migrations.AlterModelOptions(
            name='moduletype',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Tipo de modulo', 'verbose_name_plural': 'Tipos de modulos'},
        ),
        migrations.AlterField(
            model_name='externalprovider',
            name='client_id',
            field=models.TextField(default=uuid.uuid4, unique=True, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='externalprovider',
            name='client_secret',
            field=models.TextField(verbose_name='Client Secret'),
        ),
        migrations.AlterField(
            model_name='externalprovider',
            name='name',
            field=models.TextField(unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.TextField(unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='module',
            name='icon',
            field=models.TextField(blank=True, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_vertical',
            field=models.BooleanField(default=False, verbose_name='Menu vertical'),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible en menu'),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='security.moduletype', verbose_name='Tipo de modulo'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.TextField(verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='module',
            name='url',
            field=models.TextField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='moduletype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='moduletype',
            name='icon',
            field=models.TextField(blank=True, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='moduletype',
            name='name',
            field=models.TextField(unique=True, verbose_name='Nombre'),
        ),
    ]
