# Generated by Django 5.2.14 on 2026-05-17 15:48

import app.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Apellidos')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Username')),
                ('dni', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Número de cédula')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/', verbose_name='Imagen de perfil')),
                ('is_active', models.BooleanField(default=True, help_text='Determina si el usuario puede iniciar sesión', verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, help_text='Determina si el usuario puede acceder al panel de administración', verbose_name='Staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('last_password_change_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Último cambio de contraseña')),
                ('force_password_change', models.BooleanField(default=False, help_text='Si está activado, el usuario deberá cambiar su contraseña al próximo acceso', verbose_name='Forzar cambio de contraseña')),
                ('is_change_password', models.BooleanField(default=False, verbose_name='Cambio de contraseña requerido')),
                ('email_reset_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token para resetear contraseña')),
                ('token_notification', models.CharField(blank=True, help_text='Deprecated: use PushDevice instead', max_length=255, null=True, verbose_name='Token de notificación')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['username'], name='users_user_usernam_65d164_idx'), models.Index(fields=['email'], name='users_user_email_6f2530_idx'), models.Index(fields=['dni'], name='users_user_dni_287748_idx'), models.Index(fields=['is_active'], name='users_user_is_acti_ddda02_idx')],
            },
            managers=[
                ('objects', app.auth.models.CustomUserManager()),
            ],
        ),
    ]
