# Generated by Django 5.2.14 on 2026-06-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_external', models.TextField(db_index=True, unique=True, verbose_name='ID externo')),
                ('name', models.TextField(verbose_name='Nombre')),
                ('category', models.TextField(db_index=True, verbose_name='Categoria original')),
                ('gender', models.TextField(blank=True, db_index=True, verbose_name='Genero')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('price_old', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio anterior')),
                ('currency', models.TextField(default='USD', verbose_name='Moneda')),
                ('sizes', models.JSONField(blank=True, default=list, verbose_name='Tallas')),
                ('colors', models.JSONField(blank=True, default=list, verbose_name='Colores')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('image_urls', models.JSONField(blank=True, default=list, verbose_name='Imagenes')),
                ('availability', models.TextField(default='unknown', verbose_name='Disponibilidad')),
                ('store', models.TextField(db_index=True, default='modarm', verbose_name='Tienda')),
                ('extracted_at', models.DateTimeField(verbose_name='Fecha de extraccion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-extracted_at'],
                'indexes': [models.Index(fields=['category'], name='scraper_pro_categor_513958_idx'), models.Index(fields=['gender'], name='scraper_pro_gender_a010a5_idx'), models.Index(fields=['store'], name='scraper_pro_store_8d4ae6_idx')],
            },
        ),
    ]
