# Generated by Django 5.2.14 on 2026-06-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_name',
            field=models.TextField(blank=True, db_index=True, verbose_name='Nombre base (sin color)'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['base_name'], name='scraper_pro_base_na_c779f4_idx'),
        ),
    ]
