# Generated by Django 5.2.14 on 2026-07-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_scrapersource_alter_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_external',
            field=models.TextField(db_index=True, verbose_name='ID externo'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('store', 'id_external'), name='scraper_product_store_idext_uniq'),
        ),
    ]
