# Generated by Django 5.2.14 on 2026-07-10 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_product_id_external_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteOutfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_image_url', models.TextField(blank=True, default='', verbose_name='Imagen generada del try-on')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('bottom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_bottoms', to='scraper.product', verbose_name='Prenda de abajo')),
                ('top', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_tops', to='scraper.product', verbose_name='Prenda de arriba')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_outfits', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Outfit favorito',
                'verbose_name_plural': 'Outfits favoritos',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'top', 'bottom'), name='unique_user_outfit_favorite')],
            },
        ),
    ]
