# Generated by Django 5.2.14 on 2026-06-26 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Error de aplicación',
                'verbose_name_plural': 'Errores de aplicaciones',
                'ordering': ['-id'],
                'permissions': (('view_errorapp', 'Can view Error de aplicación'), ('delete_errorapp', 'Can delete Error de aplicación')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ErrorApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ErrorApi',
                'verbose_name_plural': 'ErrorApis',
                'ordering': ['-id'],
                'permissions': (('view_errorapi', 'Can view ErrorApi'), ('delete_errorapi', 'Can delete ErrorApi')),
                'default_permissions': (),
            },
        ),
    ]
