# Generated by Django 5.2.14 on 2026-06-14 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('security', '0003_alter_groupmodule_options_alter_module_options_and_more'),
        ('users', '0002_user_security_groups_alter_user_email_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.TextField(choices=[('admin', 'ADMIN'), ('mobile', 'MOBILE')], db_index=True, default='mobile', verbose_name='Tipo de usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.TextField(db_index=True, unique=True, verbose_name='Numero de cedula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(db_index=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_reset_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(blank=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False, verbose_name='Forzar cambio de contrasena'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_change_password',
            field=models.BooleanField(default=False, verbose_name='Cambio de contrasena requerido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultimo acceso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(blank=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_notification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(db_index=True, unique=True, verbose_name='Username'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='users_user_user_ty_4573bb_idx'),
        ),
    ]
