# Generated by Django 5.2.14 on 2026-06-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_user_type_alter_user_dni_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_reset_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_password_reset_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ultimo restablecimiento de contrasena"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Veces que restablecio la contrasena"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_pending",
            field=models.BooleanField(
                default=False, verbose_name="Restablecimiento de contrasena pendiente"
            ),
        ),
    ]
