# Generated by Django 5.2.14 on 2026-07-05 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0005_alter_product_id_external_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TryOnJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('garment_image_url', models.TextField(verbose_name='Imagen de la prenda')),
                ('garment_type', models.TextField(default='upper_body', verbose_name='Tipo de prenda')),
                ('status', models.TextField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], db_index=True, default='pending', verbose_name='Estado')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='try_on_results/%Y/%m/%d/', verbose_name='Resultado')),
                ('error_message', models.TextField(blank=True, verbose_name='Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='try_on_jobs', to='scraper.product', verbose_name='Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='try_on_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Prueba virtual',
                'verbose_name_plural': 'Pruebas virtuales',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='tryon_tryon_user_id_9ed735_idx')],
            },
        ),
    ]
