# Generated by Django 5.2.14 on 2026-07-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryonjob',
            name='extra_garment_image_url',
            field=models.TextField(blank=True, default='', verbose_name='Imagen de la segunda prenda'),
        ),
        migrations.AddField(
            model_name='tryonjob',
            name='extra_garment_type',
            field=models.TextField(blank=True, default='', verbose_name='Tipo de la segunda prenda'),
        ),
    ]
