# Generated by Django 5.2.14 on 2026-07-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryon', '0002_tryonjob_extra_garment_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryonjob',
            name='extra_garment_name',
            field=models.TextField(blank=True, default='', verbose_name='Nombre de la segunda prenda'),
        ),
    ]
