# Generated by Django 5.2.14 on 2026-05-17 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Número telefónico')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(blank=True, default='Ecuador', max_length=100, verbose_name='País')),
                ('department', models.CharField(choices=[('HR', 'Recursos Humanos'), ('IT', 'Información y Tecnología'), ('FINANCE', 'Finanzas'), ('SALES', 'Ventas'), ('MARKETING', 'Marketing'), ('OPERATIONS', 'Operaciones'), ('OTHER', 'Otro')], default='OTHER', max_length=50, verbose_name='Departamento')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('employee_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='ID de empleado')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Fecha de contratación')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('social_media', models.TextField(blank=True, default=dict, help_text='JSON con enlaces a redes sociales', verbose_name='Redes sociales')),
                ('is_verified', models.BooleanField(default=False, help_text='Indica si el perfil ha sido verificado', verbose_name='Verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='Gerente/Supervisor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['user__first_name', 'user__last_name'],
                'indexes': [models.Index(fields=['user'], name='profiles_us_user_id_65af30_idx'), models.Index(fields=['department'], name='profiles_us_departm_8ab3fa_idx'), models.Index(fields=['employee_id'], name='profiles_us_employe_c72099_idx')],
            },
        ),
    ]
