# Generated by Django 5.2.14 on 2026-05-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verificado'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_media',
            field=models.TextField(blank=True, default=dict, verbose_name='Redes sociales'),
        ),
    ]
