# Generated by Django 5.2.14 on 2026-06-14 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_is_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.TextField(blank=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.TextField(blank=True, default='Ecuador', verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.TextField(choices=[('rrhh', 'RECURSOS HUMANOS'), ('tecnologia', 'INFORMACION Y TECNOLOGIA'), ('finanzas', 'FINANZAS'), ('ventas', 'VENTAS'), ('marketing', 'MARKETING'), ('operaciones', 'OPERACIONES'), ('otro', 'OTRO')], default='otro', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employee_id',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='ID de empleado'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de contratacion'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_title',
            field=models.TextField(blank=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.TextField(blank=True, verbose_name='Numero telefonico'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_media',
            field=models.JSONField(blank=True, default=dict, verbose_name='Redes sociales'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion'),
        ),
        migrations.CreateModel(
            name='MobileProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.TextField(blank=True, choices=[('femenino', 'FEMENINO'), ('masculino', 'MASCULINO'), ('otro', 'OTRO'), ('no_indica', 'NO INDICA')], default='no_indica', verbose_name='Genero')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('preferred_size', models.TextField(blank=True, verbose_name='Talla preferida')),
                ('style_preferences', models.JSONField(blank=True, default=dict, verbose_name='Preferencias')),
                ('language', models.TextField(blank=True, default='es', verbose_name='Idioma')),
                ('country', models.TextField(blank=True, default='Ecuador', verbose_name='Pais')),
                ('push_token', models.TextField(blank=True, verbose_name='Token push')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil mobile',
                'verbose_name_plural': 'Perfiles mobile',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='profiles_mo_user_id_c5a54c_idx'), models.Index(fields=['country'], name='profiles_mo_country_c07951_idx'), models.Index(fields=['language'], name='profiles_mo_languag_c9e9b2_idx')],
            },
        ),
    ]
