# Generated by Django 5.2.14 on 2026-06-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_address_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileprofile',
            name='try_on_photo',
            field=models.ImageField(blank=True, null=True, upload_to='try_on/%Y/%m/%d/', verbose_name='Foto para prueba virtual'),
        ),
    ]
