# Generated by Django 5.2.14 on 2026-07-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_mobileprofile_try_on_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Onboarding completado'),
        ),
    ]
