# Generated by Django 5.2.14 on 2026-07-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_mobileprofile_onboarding_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobileprofile",
            name="onboarding_force_show",
            field=models.BooleanField(default=False, verbose_name="Forzar mostrar onboarding"),
        ),
    ]
