# Generated by Django 5.2.14 on 2026-07-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_mobileprofile_onboarding_force_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileprofile',
            name='try_on_photo_gender',
            field=models.TextField(blank=True, default='', verbose_name='Género detectado en la foto'),
        ),
    ]
